# Generated by Django 6.0 on 2025-12-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предыстория',
                'verbose_name_plural': 'Предистории',
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория инвентаря',
                'verbose_name_plural': 'Категории инвентаря',
            },
        ),
        migrations.CreateModel(
            name='InventoryCategoryCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика предмета инвентаря',
                'verbose_name_plural': 'Характеристики предмета инвентаря',
            },
        ),
        migrations.CreateModel(
            name='PClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('cast_time', models.CharField(max_length=255, verbose_name='Время накладывания')),
                ('distance', models.CharField(max_length=255, verbose_name='Дистанция')),
                ('school', models.CharField(max_length=255, verbose_name='Дистанция')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(max_length=7000, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.inventorycategory', verbose_name='Категория инвентаря')),
            ],
            options={
                'verbose_name': 'Предмет инвентаря',
                'verbose_name_plural': 'Предметы инвентаря',
            },
        ),
        migrations.CreateModel(
            name='ItemCharact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_value', models.CharField(max_length=255, verbose_name='Значение')),
                ('charact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.inventorycategorycharacteristic', verbose_name='Характеристика предмета инвентаря')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.inventoryitem', verbose_name='Предмет инвентаря')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристики',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('exp', models.IntegerField(verbose_name='Опыт')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.history', verbose_name='Предыстория')),
                ('pclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.pclass', verbose_name='Класс')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.race', verbose_name='Раса')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.inventoryitem', verbose_name='Предмет инвентаря')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Предмет инвентаря персонажа',
                'verbose_name_plural': 'Предметы инвентаря персонажа',
            },
        ),
        migrations.CreateModel(
            name='PlayerSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('bonus', models.IntegerField(verbose_name='Бонус')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.player', verbose_name='Персонаж')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.spell', verbose_name='Заклинание')),
            ],
            options={
                'verbose_name': 'Заклинание персонажа',
                'verbose_name_plural': 'Заклинания персонажа',
            },
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svalue', models.IntegerField(verbose_name='Значение')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.player', verbose_name='Персонаж')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.spell', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Базовый навык класса',
                'verbose_name_plural': 'Базовые навыки класса',
            },
        ),
        migrations.CreateModel(
            name='PClassSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svalue', models.IntegerField(verbose_name='Значение')),
                ('pclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.pclass', verbose_name='Класс')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.spell', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Базовый навык класса',
                'verbose_name_plural': 'Базовые навыки класса',
            },
        ),
    ]
