# Generated by Django 6.0 on 2025-12-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerskill',
            options={'verbose_name': 'Навык персонажа', 'verbose_name_plural': 'Навыки персонажа'},
        ),
        migrations.AlterField(
            model_name='pclassskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.skill', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='playerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.skill', verbose_name='Навык'),
        ),
    ]
