# Generated by Django 6.0 on 2025-12-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
