# Generated by Django 6.0 on 2025-12-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_race_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pclass',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
