# Generated by Django 6.0 on 2025-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pclass_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='descr',
            field=models.TextField(blank=True, max_length=7000, null=True, verbose_name='Описание'),
        ),
    ]
