# Generated by Django 6.0 on 2025-12-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_skill_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='school',
        ),
    ]
