# Generated by Django 6.0 on 2025-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_spell_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
