# Generated by Django 6.0 on 2025-12-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.history', verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.pclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.race', verbose_name='Раса'),
        ),
    ]
