# Generated by Django 6.0 on 2025-12-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='free_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Свободные очки'),
        ),
    ]
