# Generated by Django 6.0 on 2025-12-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerspell',
            name='level',
        ),
    ]
