# Generated by Django 6.0 on 2025-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_playerspell_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcharact',
            name='charact',
        ),
        migrations.RemoveField(
            model_name='itemcharact',
            name='item',
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(to='catalog.inventoryitem', verbose_name='Предмет инвентаря'),
        ),
        migrations.DeleteModel(
            name='InventoryCategoryCharacteristic',
        ),
        migrations.DeleteModel(
            name='ItemCharact',
        ),
    ]
