# Generated by Django 6.0 on 2025-12-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_itemcharact_charact_remove_itemcharact_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerItem',
        ),
    ]
